### ISSUE TITLE
mentions mission not working

### ISSUE THREAD

**Issue by paullammacau** [seLain/MissAchieve#4]
the mnetions mission did not catch user mentions correctly.

I tried to print out the number of mentions,
```
def mentions_mission(message):
    # corresponding mission settings
    mission_settings = PLUGIN_SETTINGS[inspect.stack()[0][3]]['missions']
    # get message content
    username = message.get_username()
    mentions = len(message.get_mentions()) if message.get_mentions() is not None else 0
    print('# of mentions:'+str(mentions))
```
but it always returned 0 no matter what I say to bot on public channel

**Comment by seLain** [comment]
Thanks for reporting. Please refer to seLain/mattermost_bot#21 for more info.

It's a known issue regarding Mattermost API. The API returns **mentions** value only if **the others** are mentioned in conversation -- that is, in your case, besides you and the bot (which is listening to this conversation).

So you can try to mention other users in conversation, and the **mentions** value should appear.
